name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: nightwatch-browserstack-build
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: create env file
        run: |
          touch .env
          echo BROWSERSTACK_USER =${{ secrets.BROWSERSTACK_USER }} >> .env
          echo BROWSERSTACK_KEY =${{ secrets.BROWSERSTACK_KEY }} >> .env
      - name: install typescript globally
        run: |
          npm install -g typescript
      - name: npm install
        run: |
          npm install
      - run: npm run test-browserstack
